In [4]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
print(arr1+arr)
print(arr*arr1)
print(arr**3)
print(np.sqrt(arr))
print(arr.sum())
print(np.sum(arr))
print(arr[2]+arr1[1])

[5 7 9]
[ 4 10 18]
[ 1  8 27]
[1.         1.41421356 1.73205081]
6
6
8


In [5]:
a=np.array([[10,20,30],[40,50,60]])
print(a)
print(a[0,1])
print(a[1,::-1])
print(a[0,0:1])
print(a[:1,1])
print(a[0,:2])

[[10 20 30]
 [40 50 60]]
20
[60 50 40]
[10]
[20]
[10 20]


In [12]:
#a=np.array([[10,20,30],[40,50,60]])
a=np.array([['d','a'],['c','y']])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)


2
(2, 2)
4
<U1
4


In [15]:
a=np.array([[10,20,30],[40,50,60]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.min())
print(a.max())
#print(a.median())
print(a.mean())
#print(a.mode())
print(a.std())

210
[50 70 90]
[ 60 150]
10
60
35.0
17.07825127659933


In [26]:
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(3))
print(np.full((2,2),7))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.random.rand(2,2))
print(np.random.randint(1,10,(3,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.0975074  0.37275223]
 [0.49549685 0.61438023]]
[[9 5]
 [2 3]
 [4 8]]


In [28]:
a=np.array([[1,2],[3,4]])
b=np.array([[6,7],[8,9]])
print(np.dot(a,b))
print(np.transpose(a))

[[22 25]
 [50 57]]
[[1 3]
 [2 4]]


In [39]:
a=np.array([[1,2],[3,4]])
for index,val in enumerate(a):
    for index,val in enumerate(val):
        print(f"index: {index} value: {val}")

index: 0 value: 1
index: 1 value: 2
index: 0 value: 3
index: 1 value: 4


In [31]:
str="dataScience"
for index,char in enumerate(str):
    print(f"index: {index} char: {char}")

index: 0 char: d
index: 1 char: a
index: 2 char: t
index: 3 char: a
index: 4 char: S
index: 5 char: c
index: 6 char: i
index: 7 char: e
index: 8 char: n
index: 9 char: c
index: 10 char: e


In [33]:
a=np.array([[[1,2],[3,4]]])

for i in np.nditer(a):
    print(i)


1
2
3
4
